In [2]:
## numpy libraries examples
import numpy as np

In [3]:
x = [1,2,3,4]

In [4]:
x

[1, 2, 3, 4]

In [5]:
y = np.array(x)

In [6]:
y

array([1, 2, 3, 4])

In [7]:
x = [[1,2,3,4],[5,6,7,8],[9,0,1,2]]

In [8]:
x

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 1, 2]]

In [9]:
y = np.array(x)

In [10]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [11]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
y = np.array(x)

In [14]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.zeros((3,3)) -2

array([[-2., -2., -2.],
       [-2., -2., -2.],
       [-2., -2., -2.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(50).reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
x = np.array(x)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
x.max()

9

In [24]:
x.min()

1

In [25]:
np.random.randn(5)

array([-0.354832  , -0.34095271,  0.00321115,  0.42091647,  1.02531776])

In [26]:
np.random.randint(1,100)

15

In [27]:
x.argmax()

8

In [28]:
x.argmin()

0

In [29]:
x = np.arange(1,50)

In [30]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [31]:
x[-5]

45

In [32]:
x[9]

10

In [33]:
x[1:18]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [34]:
x[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49])

In [35]:
y = x[1:9] = 20

In [36]:
y

20

In [37]:
x

array([ 1, 20, 20, 20, 20, 20, 20, 20, 20, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [38]:
y = x.copy()

In [39]:
y

array([ 1, 20, 20, 20, 20, 20, 20, 20, 20, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
y[1:10] = 3

In [41]:
y

array([ 1,  3,  3,  3,  3,  3,  3,  3,  3,  3, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [42]:
x = np.arange(25).reshape(5,5)

In [43]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
x[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [45]:
x[2,2]

12

In [46]:
y = np.arange(25)

In [47]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
y[y>13]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
x = np.arange(25,50)

In [50]:
x

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
z = x + y

In [52]:
z

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73])

In [53]:
np.sin(x)

array([-0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388,
       -0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
       -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539,
        0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
        0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265])

In [54]:
x =np.arange(10).reshape(2,5)

In [55]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
y = np.arange(10,20).reshape(2,5)

In [57]:
x + y

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [58]:
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
x * y

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [60]:
x / y

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

In [61]:
x // y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [62]:
x ** y

array([[          0,           1,        4096,     1594323,   268435456],
       [  452807053,  -683606016, -2094633337,           0,  -400556711]],
      dtype=int32)

In [63]:
x.sum()

45

In [64]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [66]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

x = arr[arr%2==1]

print(x)

[1 3 5 7 9]


In [67]:
x = np.arange(10)
y = np.arange(6)


In [68]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
y

array([0, 1, 2, 3, 4, 5])

In [70]:
np.intersect1d(x,y)

array([0, 1, 2, 3, 4, 5])

In [71]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [72]:
a[(a>-5) & (a<=10)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# pandas libraries examples
import pandas as pd

In [74]:
x = ['a','b','c','d','e']
y = [1,2,3,4,5]
z = {1:'a', 2:'b', 3:'c', 4:'d', 5:'e' }

In [75]:
a = pd.Series(data = x)
a

0    a
1    b
2    c
3    d
4    e
dtype: object

In [76]:
type(a)

pandas.core.series.Series

In [77]:
a = pd.Series(data = x, index = y)
a

1    a
2    b
3    c
4    d
5    e
dtype: object

In [78]:
x = ['a','b','c','d','e']
y = [1, 1, 1, 1, 1]
z = {1:'a', 2:'b', 3:'c', 4:'d', 5:'e' }

In [79]:
a = pd.Series(data = x, index = y)
a

1    a
1    b
1    c
1    d
1    e
dtype: object

In [80]:
a = pd.Series( x, y)
a

1    a
1    b
1    c
1    d
1    e
dtype: object

In [81]:
x = ['a','b','c','d','e']
x2 = ['a', 'b', 'c', 'd', 'e']
y = [1, 2, 3, 4, 5]
z = {1:'a', 2:'b', 3:'c', 4:'d', 5:'e' }
a = pd.Series(y, x)
b = pd.Series(y, x2) 

In [82]:
a + b

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [83]:
a['b']

2

In [84]:
a['b':]

b    2
c    3
d    4
e    5
dtype: int64

In [85]:
A = [1,2,3,4]
B = [5,6,7,8]
C = [9,10,11,12]
D = [13,14,15,16]
E = [17,6,5,2]


In [86]:
df = pd.DataFrame([A, B, C, D, E],['r1','r2','r3','r4','r5'],['c1', 'c2', 'c3', 'c4'])
df

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17   6   5   2

In [87]:
import emoji

In [88]:
print(emoji.emojize('Python is very easy!!! :thumbs_up:'))

Python is very easy!!! 👍


In [89]:
# emoji shortcut key for windows is window + '.' or window + ';'

In [90]:
print('👀')

👀


In [91]:
df

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17   6   5   2

In [92]:
df['c5'] = df['c3'] + df['c4']


In [93]:
df

c1  c2  c3  c4  c5
r1   1   2   3   4   7
r2   5   6   7   8  15
r3   9  10  11  12  23
r4  13  14  15  16  31
r5  17   6   5   2   7

In [94]:
df.drop('r1') # for deleting row

c1  c2  c3  c4  c5
r2   5   6   7   8  15
r3   9  10  11  12  23
r4  13  14  15  16  31
r5  17   6   5   2   7

In [95]:
df

c1  c2  c3  c4  c5
r1   1   2   3   4   7
r2   5   6   7   8  15
r3   9  10  11  12  23
r4  13  14  15  16  31
r5  17   6   5   2   7

In [96]:
df.drop('r1', inplace = True) #deleting r1 row permanently

In [97]:
df

c1  c2  c3  c4  c5
r2   5   6   7   8  15
r3   9  10  11  12  23
r4  13  14  15  16  31
r5  17   6   5   2   7

In [98]:
df.drop('c5', axis = 1)  # deleting the 'c5' column temporarily

c1  c2  c3  c4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17   6   5   2

In [99]:
df

c1  c2  c3  c4  c5
r2   5   6   7   8  15
r3   9  10  11  12  23
r4  13  14  15  16  31
r5  17   6   5   2   7

In [100]:
df.drop('c5', axis = 1, inplace = True)  #deleting 'c5' column permanently

In [101]:
df

c1  c2  c3  c4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17   6   5   2

In [102]:
df > 3

c1    c2    c3     c4
r2  True  True  True   True
r3  True  True  True   True
r4  True  True  True   True
r5  True  True  True  False

In [103]:
df[df['c1']>15]['c1']

r5    17
Name: c1, dtype: int64

In [104]:
df[(df['c1']>9) & (df['c4']>2)]

c1  c2  c3  c4
r4  13  14  15  16

In [105]:
Y = {'a':[1,2,3,4], 'b':[5,6,7,np.nan], 'c':[8,9,np.nan,np.nan], 'd':[10,np.nan,np.nan,np.nan]}

In [106]:
df = pd.DataFrame(Y)

In [107]:
df

a    b    c     d
0  1  5.0  8.0  10.0
1  2  6.0  9.0   NaN
2  3  7.0  NaN   NaN
3  4  NaN  NaN   NaN

In [108]:
df['b'].fillna(-1)

0    5.0
1    6.0
2    7.0
3   -1.0
Name: b, dtype: float64

In [109]:
df.fillna(-3)

a    b    c     d
0  1  5.0  8.0  10.0
1  2  6.0  9.0  -3.0
2  3  7.0 -3.0  -3.0
3  4 -3.0 -3.0  -3.0

In [110]:
df['b'].fillna(value = df['b'].mean())

0    5.0
1    6.0
2    7.0
3    6.0
Name: b, dtype: float64

In [111]:
df.fillna(value = df.mean())

a    b    c     d
0  1  5.0  8.0  10.0
1  2  6.0  9.0  10.0
2  3  7.0  8.5  10.0
3  4  6.0  8.5  10.0

In [112]:
p = { 'productsale':['laptop','laptop', 'mobile', 'printer','mobile','printer'], 'days':['sunday', 'monday', 'tuesday', 'wednesday','thursday','friday'], 'salesunit':[100,500,300,600,700,800]}


In [113]:
df = pd.DataFrame(p)
df

productsale       days  salesunit
0      laptop     sunday        100
1      laptop     monday        500
2      mobile    tuesday        300
3     printer  wednesday        600
4      mobile   thursday        700
5     printer     friday        800

In [114]:
x = df.groupby('productsale')
x

In [115]:
x.mean()

salesunit
productsale           
laptop             300
mobile             500
printer            700

In [116]:
x.sum()

salesunit
productsale           
laptop             600
mobile            1000
printer           1400

In [117]:
x.std() #standard deviation of x 

salesunit
productsale            
laptop       282.842712
mobile       282.842712
printer      141.421356

In [118]:
x.max()

days  salesunit
productsale                      
laptop          sunday        500
mobile         tuesday        700
printer      wednesday        800

In [119]:
x.describe()

salesunit                                                      
                count   mean         std    min    25%    50%    75%    max
productsale                                                                
laptop            2.0  300.0  282.842712  100.0  200.0  300.0  400.0  500.0
mobile            2.0  500.0  282.842712  300.0  400.0  500.0  600.0  700.0
printer           2.0  700.0  141.421356  600.0  650.0  700.0  750.0  800.0

In [120]:
x.describe().transpose()

productsale          laptop      mobile     printer
salesunit count    2.000000    2.000000    2.000000
          mean   300.000000  500.000000  700.000000
          std    282.842712  282.842712  141.421356
          min    100.000000  300.000000  600.000000
          25%    200.000000  400.000000  650.000000
          50%    300.000000  500.000000  700.000000
          75%    400.000000  600.000000  750.000000
          max    500.000000  700.000000  800.000000

In [121]:
x1 = { 'a':[1,2,3], 'b':[3,5,6] }
y1 = { 'c':[4,7,8], 'd':[7,3,2] }

In [122]:
x = pd.DataFrame(x1, index = ['p1','p2','p3'])
y = pd.DataFrame(y1, index = ['p1','p2','p3'])

In [123]:
x

a  b
p1  1  3
p2  2  5
p3  3  6

In [124]:
y

c  d
p1  4  7
p2  7  3
p3  8  2

In [125]:
x.join(y)

a  b  c  d
p1  1  3  4  7
p2  2  5  7  3
p3  3  6  8  2

In [126]:
x.join(y, how = 'left')

a  b  c  d
p1  1  3  4  7
p2  2  5  7  3
p3  3  6  8  2

In [127]:
x.join(y, how = 'outer')

a  b  c  d
p1  1  3  4  7
p2  2  5  7  3
p3  3  6  8  2

In [128]:
x.join(y, how = 'inner')

a  b  c  d
p1  1  3  4  7
p2  2  5  7  3
p3  3  6  8  2

In [129]:
x1 = {'a':[1,1,1,1,1], 'b':[1,1,1,1,1], 'c':[1,1,1,1,1], 'd':[1,1,1,1,1], 'e':[1,1,1,1,1]}
x2 = {'e':[1,1,1,1,1], 'f':[1,1,1,1,1], 'g':[1,1,1,1,1], 'h':[1,1,1,1,1], 'i':[1,1,1,1,1]}
x3 = {'a':[3,3,3,3,3], 'b':[3,3,3,3,3], 'c':[3,3,3,3,3], 'd':[3,3,3,3,3], 'e':[3,3,3,3,3]}

In [130]:
df1 = pd.DataFrame(x1, index = [1,2,3,4,5])
df2 = pd.DataFrame(x2, index = [1,2,3,4,5])
df3 = pd.DataFrame(x3, index = [5,6,7,8,9])

In [131]:
pd.concat([df1,df2], axis = 1)

a  b  c  d  e  e  f  g  h  i
1  1  1  1  1  1  1  1  1  1  1
2  1  1  1  1  1  1  1  1  1  1
3  1  1  1  1  1  1  1  1  1  1
4  1  1  1  1  1  1  1  1  1  1
5  1  1  1  1  1  1  1  1  1  1

In [132]:
pd.concat([df1,df2])

a    b    c    d  e    f    g    h    i
1  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
2  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
3  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
4  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
5  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
2  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
3  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
4  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
5  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0

In [133]:
pd.concat([df1,df2,df3])

a    b    c    d  e    f    g    h    i
1  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
2  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
3  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
4  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
5  1.0  1.0  1.0  1.0  1  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
2  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
3  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
4  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
5  NaN  NaN  NaN  NaN  1  1.0  1.0  1.0  1.0
5  3.0  3.0  3.0  3.0  3  NaN  NaN  NaN  NaN
6  3.0  3.0  3.0  3.0  3  NaN  NaN  NaN  NaN
7  3.0  3.0  3.0  3.0  3  NaN  NaN  NaN  NaN
8  3.0  3.0  3.0  3.0  3  NaN  NaN  NaN  NaN
9  3.0  3.0  3.0  3.0  3  NaN  NaN  NaN  NaN

In [134]:
pd.concat([df1,df2,df3], axis = 1)

a    b    c    d    e    e    f    g    h    i    a    b    c    d    e
1  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN
2  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN
3  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN
4  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  NaN  NaN  NaN  NaN  NaN
5  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  3.0  3.0  3.0  3.0  3.0
6  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  3.0  3.0  3.0  3.0  3.0
7  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  3.0  3.0  3.0  3.0  3.0
8  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  3.0  3.0  3.0  3.0  3.0
9  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  3.0  3.0  3.0  3.0  3.0

In [135]:
pd.merge(df1, df2)

a  b  c  d  e  f  g  h  i
0   1  1  1  1  1  1  1  1  1
1   1  1  1  1  1  1  1  1  1
2   1  1  1  1  1  1  1  1  1
3   1  1  1  1  1  1  1  1  1
4   1  1  1  1  1  1  1  1  1
5   1  1  1  1  1  1  1  1  1
6   1  1  1  1  1  1  1  1  1
7   1  1  1  1  1  1  1  1  1
8   1  1  1  1  1  1  1  1  1
9   1  1  1  1  1  1  1  1  1
10  1  1  1  1  1  1  1  1  1
11  1  1  1  1  1  1  1  1  1
12  1  1  1  1  1  1  1  1  1
13  1  1  1  1  1  1  1  1  1
14  1  1  1  1  1  1  1  1  1
15  1  1  1  1  1  1  1  1  1
16  1  1  1  1  1  1  1  1  1
17  1  1  1  1  1  1  1  1  1
18  1  1  1  1  1  1  1  1  1
19  1  1  1  1  1  1  1  1  1
20  1  1  1  1  1  1  1  1  1
21  1  1  1  1  1  1  1  1  1
22  1  1  1  1  1  1  1  1  1
23  1  1  1  1  1  1  1  1  1
24  1  1  1  1  1  1  1  1  1

In [136]:
pd.merge(df1, df2, how = 'inner')

a  b  c  d  e  f  g  h  i
0   1  1  1  1  1  1  1  1  1
1   1  1  1  1  1  1  1  1  1
2   1  1  1  1  1  1  1  1  1
3   1  1  1  1  1  1  1  1  1
4   1  1  1  1  1  1  1  1  1
5   1  1  1  1  1  1  1  1  1
6   1  1  1  1  1  1  1  1  1
7   1  1  1  1  1  1  1  1  1
8   1  1  1  1  1  1  1  1  1
9   1  1  1  1  1  1  1  1  1
10  1  1  1  1  1  1  1  1  1
11  1  1  1  1  1  1  1  1  1
12  1  1  1  1  1  1  1  1  1
13  1  1  1  1  1  1  1  1  1
14  1  1  1  1  1  1  1  1  1
15  1  1  1  1  1  1  1  1  1
16  1  1  1  1  1  1  1  1  1
17  1  1  1  1  1  1  1  1  1
18  1  1  1  1  1  1  1  1  1
19  1  1  1  1  1  1  1  1  1
20  1  1  1  1  1  1  1  1  1
21  1  1  1  1  1  1  1  1  1
22  1  1  1  1  1  1  1  1  1
23  1  1  1  1  1  1  1  1  1
24  1  1  1  1  1  1  1  1  1

In [137]:
pd.merge(df1, df3, how = 'inner')

Empty DataFrame
Columns: [a, b, c, d, e]
Index: []

In [138]:
pd.merge(df1, df3, how = 'inner', on='a')

Empty DataFrame
Columns: [a, b_x, c_x, d_x, e_x, b_y, c_y, d_y, e_y]
Index: []

In [139]:
x =pd.DataFrame({'a':[1,2,3,4,5], 'b':[20,30,40,50,60]})
x

a   b
0  1  20
1  2  30
2  3  40
3  4  50
4  5  60

In [140]:
x.index

RangeIndex(start=0, stop=5, step=1)

In [141]:
x.columns

Index(['a', 'b'], dtype='object')

In [142]:
x['b'].sum()

200

In [143]:
def inc(x):
    x = x + 100
    return x

In [144]:
x

a   b
0  1  20
1  2  30
2  3  40
3  4  50
4  5  60

In [145]:
x['b'].apply(inc)

0    120
1    130
2    140
3    150
4    160
Name: b, dtype: int64

In [146]:
x =pd.DataFrame({'a':[1,2,3,4,5], 'b':[20,30,50,20,10]})
x

a   b
0  1  20
1  2  30
2  3  50
3  4  20
4  5  10

In [147]:
x.sort_values('b')

a   b
4  5  10
0  1  20
3  4  20
1  2  30
2  3  50

In [150]:
x['b'].value_counts()

20    2
30    1
10    1
50    1
Name: b, dtype: int64

In [151]:
x['b'].unique()

array([20, 30, 50, 10], dtype=int64)

In [152]:
x['b'].nunique()

4

In [153]:
x.isnull()

a      b
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False

In [154]:
pwd

'C:\\Users\\Hacker\\Documents\\Python Scripts'